# -*- coding: utf-8 -*-
"""Calculator project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16PlHEgtvxhOpk993iguNj5WM_EZoZkSR
"""

! pip install streamlit -q

!wget -q -O - ipv4.icanhazip.com

! streamlit run app.py & npx localtunnel --port 8501